create table if not exists public.misaki_relationship_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  intimacy_level text not null default 'initial' check (intimacy_level in ('initial','familiar','intimate','very_intimate')),
  intimacy_points integer not null default 0 check (intimacy_points >= 0),
  emotion_state jsonb not null default '{"primary":"neutral","intensity":0}'::jsonb,
  action_state text not null default 'NORMAL' check (action_state in ('NORMAL','WAIT','TEASE','SULK','CHASE','PULL','RECONNECT')),
  last_user_message_at timestamptz,
  last_misaki_message_at timestamptz,
  last_interaction_at timestamptz,
  silence_started_at timestamptz,
  state_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.misaki_relationship_state enable row level security;
revoke all on table public.misaki_relationship_state from public, anon;
revoke all on table public.misaki_relationship_state from authenticated;
grant select on table public.misaki_relationship_state to authenticated;
grant select, insert, update, delete on table public.misaki_relationship_state to service_role;

create policy "permanent users can read own relationship state"
on public.misaki_relationship_state for select to authenticated
using ((select auth.uid()) = user_id and coalesce((select (auth.jwt()->>'is_anonymous')::boolean), false) = false);

create table if not exists public.misaki_relationship_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  source_message_id bigint references public.conversations(id) on delete set null,
  source_delivery_id uuid references public.misaki_proactive_deliveries(id) on delete set null,
  before_state jsonb,
  after_state jsonb,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists misaki_relationship_events_user_created_idx on public.misaki_relationship_events(user_id, created_at desc);
create index if not exists misaki_relationship_events_source_message_idx on public.misaki_relationship_events(source_message_id) where source_message_id is not null;
create index if not exists misaki_relationship_events_source_delivery_idx on public.misaki_relationship_events(source_delivery_id) where source_delivery_id is not null;

alter table public.misaki_relationship_events enable row level security;
revoke all on table public.misaki_relationship_events from public, anon;
revoke all on table public.misaki_relationship_events from authenticated;
grant select on table public.misaki_relationship_events to authenticated;
grant select, insert, update, delete on table public.misaki_relationship_events to service_role;

create policy "permanent users can read own relationship events"
on public.misaki_relationship_events for select to authenticated
using ((select auth.uid()) = user_id and coalesce((select (auth.jwt()->>'is_anonymous')::boolean), false) = false);
