-- User feedback on individual Misaki replies. Feedback is quality telemetry only:
-- it must never change relationship points, emotion, action, or generation behavior directly.
create table if not exists public.misaki_reply_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null,
  rating text not null check (rating in ('good','bad')),
  reason text null check (reason is null or reason in ('unnatural','too_cold','distance_wrong','forgot_context','repetitive','other')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, request_id)
);
alter table public.misaki_reply_feedback enable row level security;
revoke all on table public.misaki_reply_feedback from public, anon, authenticated;
grant select, insert, update on table public.misaki_reply_feedback to service_role;
